server:
  port: 8761

spring:
  application:
    name: service-discovery
#    spring dataSource를 비활성화하고 자동 구성을 막기 위한 옵션 추가
  datasource:
    driver-class-name: none
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

eureka:
  client:
    register-with-eureka: false # 유레카 서비스에 (자신)등록 여부
    fetch-registry: false # (유레카 클라이언트 기반) 다른 서비스들의 정보를 fetch 유무
    service-url:
      defaultZone: http://localhost:8761/eureka/ # 설정을 해놓지 않으면 기본 http://localhost:8761/ 로 연동됩니다. 유레카 서버가 다른 유레카 서버와 통신할때 사용하는 기본 url

  server:
    wait-time-in-ms-when-sync-empty: 5  # 서버가 요청을 받기 전 대기할 초기 시간 지정(ms) 거의 대기 없음 (default 5분 : 상용에서는 모든 서비스가 등록되길 기다리기 위해 5분 후 정보를 공유합니다. )


management:
  endpoints:
    web:
      exposure:
        include: "*"
